-- MySQL Script generated by MySQL Workbench
-- 03/21/17 14:01:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlsolicitudes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `social_programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_programs` (
  `social_program_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`social_program_id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `towns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `towns` (
  `town_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`town_id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `applications` (
  `application_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(100) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `beneficiary` VARCHAR(250) NOT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  `date` DATE NOT NULL,
  `town_id` INT(11) NOT NULL,
  `social_program_id` INT(11) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`application_id`),
  INDEX `fk_applications_towns1_idx` (`town_id` ASC),
  INDEX `fk_applications_social_programs1_idx` (`social_program_id` ASC),
  CONSTRAINT `fk_applications_social_programs1`
    FOREIGN KEY (`social_program_id`)
    REFERENCES `social_programs` (`social_program_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applications_towns1`
    FOREIGN KEY (`town_id`)
    REFERENCES `towns` (`town_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
