/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cruiz90.presidencia.interfaces;

import com.cruiz90.presidencia.database.models.Town;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.BevelBorder;

/**
 *
 * @author ISC. Carlos Alfredo Ruiz Calderon <car.ruiz90@gmail.com>
 */
public class TownPanel extends JPanel implements ActionListener {

    private List<JButton> townsButtonList;

    /**
     * Creates new form ComunityPanel
     */
    public TownPanel() {
        initComponents();
        setupScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comunidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 500));
        setRequestFocusEnabled(false);
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void setupScreen() {
        JButton manager = new JButton();
        manager.setBounds(10, 30, 50, 50);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/com/cruiz90/presidencia/images/list.png")).getImage().getScaledInstance(manager.getWidth(), manager.getHeight(), Image.SCALE_SMOOTH));
        manager.setIcon(imageIcon);
        manager.setToolTipText("Administrar comunidades");
        manager.addActionListener(managerListener());
        add(manager);

        JButton usersManager = new JButton();
        usersManager.setBounds(70, 30, 50, 50);
        imageIcon = new ImageIcon(new ImageIcon(getClass().getResource("/com/cruiz90/presidencia/images/users.png")).getImage().getScaledInstance(usersManager.getWidth(), usersManager.getHeight(), Image.SCALE_SMOOTH));
        usersManager.setIcon(imageIcon);
        usersManager.setToolTipText("Administrar usuarios");
        usersManager.addActionListener(usersManagerListener());
        add(usersManager);

        JPanel townssGrid = new JPanel();
        townssGrid.setLayout(new GridLayout(4, 5, 3, 3));

        List<Town> towns = Town.getAll();
        townsButtonList = new ArrayList<>();
        for (Town town : towns) {
            JButton button = new JButton(town.getName());
            button.setActionCommand(town.getTownId().toString());
            townsButtonList.add(button);
            button.addActionListener(this);
            townssGrid.add(button, 0, 0);
        }
        townssGrid.setBounds(10, 100, 850, 290);
        townssGrid.setBorder(BorderFactory.createSoftBevelBorder(BevelBorder.RAISED));
        add(townssGrid);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        JPanel programs = new SocialProgramsPanel(e.getActionCommand());
        programs.setBounds(10, 120, 870, 400);
        parentFrame.add(programs);
        parentFrame.remove(this);
        parentFrame.revalidate();
        parentFrame.repaint();
    }

    private ActionListener managerListener() {
        return new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                changeContentPanel(new TownsManager());
            }
        };
    }

    private ActionListener usersManagerListener() {
        return new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                changeContentPanel(new UsersManager());
            }
        };
    }

    private void changeContentPanel(JPanel panel) {
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        panel.setBounds(10, 120, 870, 400);
        parentFrame.add(panel);
        parentFrame.remove(this);
        parentFrame.revalidate();
        parentFrame.repaint();
    }
}
